### ISSUE TITLE
Permanent white theme

### ISSUE THREAD

**Issue by MateusCapistrano** [Hiberbee/code-highlight-themes#108]
**Describe the bug**
After the last update i'm stuck in a "white" theme. only the background of the code is white, the rest seens normal

**To Reproduce**
1. Use the theme

**Expected behavior**
The normal theme

**Screenshots**
![image](https://github.com/hiberbee/themes/assets/144906298/26302b8d-cf31-42e3-a44e-574c79e94682)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by OSuwaidi** [comment]
Same issue here with Windows 10 after the last update: 2023.10.29.1816

**Comment by LukeyR** [comment]
I had this after update but also after rolling back to a previous version due to #107, check Editor>Color Scheme, mine got reset to "Classic light"

**Comment by austinChappell** [comment]
In case it's helpful for tracking down the issue, here is the stacktrace in my IDE. This was in RubyMine 2023.2.4 on MacOS Sonoma 14.0. 

```
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.hiberbee.ExtraIconProvider) [Plugin: com.hiberbee.intellij.hiberbee-theme]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1067)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:69)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:30)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:474)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:248)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.kt:43)
	at com.intellij.util.IconUtil.getProviderIcon(IconUtil.kt:226)
	at com.intellij.util.IconUtil.computeFileIconImpl(IconUtil.kt:167)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.kt:159)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:392)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:391)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.doUpdateFileIcon$intellij_platform_ide_impl(EditorsSplitters.kt:391)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invokeSuspend(EditorsSplitters.kt:135)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invoke(EditorsSplitters.kt)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invoke(EditorsSplitters.kt)
	at com.intellij.openapi.fileEditor.impl.MergingUpdateChannel.start(MergingUpdateChannel.kt:39)
	at com.intellij.openapi.fileEditor.impl.MergingUpdateChannel$start$1.invokeSuspend(MergingUpdateChannel.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: com.hiberbee.ExtraIconProvider PluginClassLoader(plugin=PluginDescriptor(name=Hiberbee Theme, id=com.hiberbee.intellij.hiberbee-theme, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/RubyMine2023.2/plugins/Hiberbee Theme, version=2023.10.29.1816, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1607)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:947)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:48)
	... 49 more
```

**Comment by stylin-software** [comment]
I have the same issue on OSX. Suffered a sprained retina with the unexpected brightness

**Comment by vladyslavvolkov** [comment]
Thanks guys, my bad, fix is upcoming in few days.

Actually, thats weird how plugin passed Jetbrains plugin checker

**Comment by vladyslavvolkov** [comment]
Follow [2023.11.4.1839](https://github.com/hiberbee/themes/releases/tag/2023.11.4.1839) in marketplace in couple days

**Comment by shouwei** [comment]
> Follow [2023.11.4.1839](https://github.com/hiberbee/themes/releases/tag/2023.11.4.1839) in marketplace in couple days

I manually installed this version, and although there is no error report, the background is still white.

**Comment by k-osiecki** [comment]
Installed 2023.11.4.1839 from disk and still have white background in editor and console - env info:
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry:
    analyze.exceptions.on.the.fly=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.hiberbee.intellij.hiberbee-theme (2023.11.4.1839)
    monokai-pro (1.10)
    org.intellij.RegexpTester (2.2.0)
    org.rust.lang (0.4.201.5424-232)
    com.vecheslav.darculaSolidTheme (1.0.3)
    com.markskelton.one-dark-theme (5.9.0)
    com.intellij.properties.bundle.editor (232.8660.88)
    com.intellij.kubernetes (232.10203.2)
    com.jetbrains.jax.ws (232.8660.142)
    com.intellij.spring.batch (232.8660.142)
    org.jetbrains.kotlin (232-1.9.20-release-507-IJ10072.27)
    PlantUML integration (7.3.0-IJ2023.2)
    google-java-format (1.17.0.0)
    dev.flikas.idea.spring.boot.assistant.plugin (0.14.3)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    com.intellij.guice (232.8660.142)
    com.intellij.aspectj (232.8660.142)
    com.intellij.javaee.batch (232.8660.142)
    plantuml-parser (0.0.6)
    com.haulmont.jpab (2023.4.0-232)
    org.intellij.scala (2023.2.27)
    MavenRunHelper (4.26.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.40.7)
    Pythonid (232.10203.10)
    net.ashald.envfile (3.4.1)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.intellij.bigdatatools.core (232.10203.10)
    com.intellij.bigdatatools.kafka (232.10203.10)
    com.intellij.bigdatatools.binary.files (232.10072.27)
    com.intellij.bigdatatools.rfs (232.10203.10)
    com.intellij.bigdatatools.metastore.core (232.10203.10)
    com.intellij.bigdatatools.flink (232.10072.27)
    com.intellij.bigdatatools.spark (232.10072.27)
    com.intellij.bigdatatools.zeppelin (232.10072.27)
    com.intellij.bigdatatools (232.10072.27)
    mobi.hsz.idea.gitignore (4.5.2)
    com.brandiico.jetbrains-nightfall-theme (1.1.9)
    com.intellij.plugins.html.instantEditing (232.8660.142)

Kotlin: 232-1.9.20-release-507-IJ10072.27

**Comment by vladyslavvolkov** [comment]
Is `Hiberbee Dark` theme available in [**Editor** - **Color Scheme**](jetbrains://idea/settings?name=Editor--Color+Scheme) dropdown? Most likely from old version provided scheme was dropped.

**Comment by k-osiecki** [comment]
Yes, this was exactly what happened, I opened settings/editor/color scheme and changed default light theme to hiberbee and everything is ok.
Knowing that I removed my comment.


Thanks.
K+

**Comment by stylin-software** [comment]
I have updated the plugin... Its still bright, its still white...
I have selected the correct dark theme from the drop down, switched between other themes that are working, and then back to dark, and it is still super white!

Is there a way I can roll back to an older version that works properly?

**Comment by vladyslavvolkov** [comment]
@stylin-software Frankly, I can't reproduce that issue. I will try to debug more, in meanwhile you can import color scheme manually from this repo. 

In settings:

![image](https://github.com/hiberbee/themes/assets/1200484/c6441326-6554-464e-ae87-7320639e2508)

Download this file: [src/intellij/src/main/resources/colors/Dark.xml](https://raw.githubusercontent.com/hiberbee/themes/latest/src/intellij/src/main/resources/colors/Dark.xml)

Also, before importing, could you please check **Restore defaults** from the same menu as on screenshot, with my theme selected? Maybe that could help as well

**Comment by vladyslavvolkov** [comment]
I've updated release flow, so each tagged release will be reflected in github release with `jar` artifact as well

https://github.com/hiberbee/themes/releases/tag/2023.11.8.132

You can install plugin of specific version manually (`Install plugin from disk` in **Settings** - **Plugins**)

**Comment by bitjerry** [comment]
> @stylin-software Frankly, I can't reproduce that issue. I will try to debug more, in meanwhile you can import color scheme manually from this repo.
> 
> In settings:
> 
> ![image](https://user-images.githubusercontent.com/1200484/281199178-c6441326-6554-464e-ae87-7320639e2508.png)
> 
> Download this file: [src/intellij/src/main/resources/colors/Dark.xml](https://raw.githubusercontent.com/hiberbee/themes/latest/src/intellij/src/main/resources/colors/Dark.xml)
> 
> Also, before importing, could you please check **Restore defaults** from the same menu as on screenshot, with my theme selected? Maybe that could help as well

Is the current color scheme dark?  I have updated the version to 2023.11.8.132, and there is no hiberbee in the options.

![image](https://github.com/hiberbee/themes/assets/52879142/df06e2f4-4be0-4e34-8838-2721b75fba02)

**Comment by vladyslavvolkov** [comment]
@bitjerry could you check this patched one? https://github.com/hiberbee/themes/releases/tag/2023.11.8.1038

**Comment by bitjerry** [comment]
> @bitjerry could you check this patched one? https://github.com/hiberbee/themes/releases/tag/2023.11.8.1038

I saw this option, it works well 😘

![image](https://github.com/hiberbee/themes/assets/52879142/e9b83be5-90b4-486e-a1ad-463c739c3633)
